### ISSUE TITLE
Terminal fails to launch

### ISSUE THREAD

**Issue by kickthedragon** [vertexclique/tokamak-terminal#4]
I did a clean install of my OS fedora 23 today, along with rust, and racer.  Ran the command `apm install tokamak` after i Installed Atom.  Now when i try to launch tokamak-terminal, i just see a black screen with no error output.  I posted a screenshot to show.  
![screenshot from 2016-04-23 00-18-14](https://cloud.githubusercontent.com/assets/5422123/14759239/05b789b2-08e9-11e6-8db7-c7ad12701546.png)

**Comment by flo-l** [comment]
I'm having the same problem, also on Fedora 23!

**Comment by flo-l** [comment]
It seems to work with atom 1.7.4!

**Comment by Llano** [comment]
Doesn't work for me with 1.7.4. Same problem.

**Comment by flo-l** [comment]
I have removed the whole .atom folder and reinstalled tokamak. You could try that!

**Comment by Llano** [comment]
Unfortunately that didn't work fo me either.

**Comment by ELD** [comment]
@Llano, @flo-l the issue, I think, has to do with some native Node modules. The original package this was forked from fixed them, but the changes haven't made it here since the package is relatively out of date.

**Comment by dizergin** [comment]
win10 - the same problem

**Comment by rofrol** [comment]
Instruction how to fix manually https://github.com/vertexclique/tokamak-terminal/issues/10#issuecomment-259943572

**Comment by vertexclique** [comment]
updated in `v10.0.1`

**Comment by flo-l** [comment]
works for me, thx!
